### ISSUE TITLE
Push wallet-proxy images to dockerhub

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-wallet-proxy#11]
**Task description**

Currently they are pushed to AWS container registry which makes it impossible to easily build publicly available configurations that use the wallet-proxy.
Since there is no reason that the images are private we should publish them on dockerhub.

**Sub-tasks**
- [ ] the builder image should use the public base image
- [ ] publish images on dockerhub
- [ ] update deployment scripts to use the public images

**Comment by abizjak** [comment]
Closed by #22
