### ISSUE TITLE
Support transfers with memos

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-wallet-proxy#18]
**Task description**

The mobile wallet will need to submit and query 3 new transaction types, transfers with metadata.

To enable submission we won't really have to do anything since the proxy does not check transaction payload.

But queries will need to be updated.

**Sub-tasks**
- [ ] Update getSumissionStatus to support 3 new transaction types. They should behave the same as the current transfers statuses, but have the additional memo field.
- [ ] Update the `v0/accTransactions` endpoint to be compatible with new transactions. This will enable existing wallets to receive transfers with memos, but without displaying the memos. To achieve this the following changes should be made
     - [ ] add handling of three new transfer types to `formatEntry`. They should be handled in the same ways as existing transfers, the memo being ignored.
     - [ ] The `renderTransactionSummaryType` must be parameterized by a version so that for the `v0/accTransactions` endpoint it will map new TransferWithMetadata to Transfer, etc
- [ ] Add a new endpoint `v1/accTransactions` that behaves analogously to `v0/accTransactions`, but also returns memos for the three new transaction types.
- [ ] Extend the `v0/transactionCost` endpoint with support for additional transaction types. For the new transactions an additional query parameter should be added, e.g., `metadataSize` that will be used for calculating the cost.
