### ISSUE TITLE
Add better logging and metric collection

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-wallet-proxy#20]
**Task description**

The wallet-proxy does not record any metrics about the response latencies but it would be valuable to have them. Similarly, logging is sometimes inadequate for issue analysis.

- [ ] Record or log response latencies. Logging would already be valuable, but the ideal would likely be to expose them in a standard way like we do with the node, so via Prometheus.
   - [ ] Response time from database queries to the transaction log database.
   - [ ] Response time for node queries.
- [ ] Log additional data with requests.
  - [ ] For account creation transactions (in submitCredential) log the address of the account that would be created.
  - [ ] For transaction submission log the sender account (and maybe some other items from the header such as expiry and nonce).
