### ISSUE TITLE
Remove the extra symbols in parameter

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-wallet-proxy#73]
**Description**

When invoking another contract inside of a smart contract function then the parameter is displayed with several extra symbols in the mobile wallet as well as in `concordium-client`. Can we decode the values or remove the extra symbols?

http://wallet-proxy.stagenet.concordium.com/v1/accTransactions/3SB8kJchHEn1RLYqfuCwi1hsQaXvKVmUa9dxMAZGPKhwnpJavP?order=d

./concordium-client transaction status 2abff58d83d831257ed77cdef5181204d7789ff794b88af17f59bdac98047b70 --grpc-port [yourPort] --grpc-ip [YourConnection]
./concordium-client transaction status 9aaa50bdd6d864219189fbd0db11457df43084fddba42954eda8bdc0d0fc80f0 --grpc-port [YourPort] --grpc-ip [YourConnection]

```
sent
message to function
'"counter.upgradeSeveralTimesDifferentSmartContracts"' with
'Parameter {parameter =
":8\244_\192\214\208\NAKm\173\128\209\226\203\SI\"\251TQ\STX\169|H\149<\238D\239H\DLER\162:8\244_\192\214\208\NAKm\173\128\209\226\203\SI\"\251TQ\STX\169|H\149<\238D\239H\DLER\162\192W\215\244w%(|\GS\SYN^\151#y^M\229\184K\181\248\222\242\185Z\215\187\177/\253\160~\SOH\t\NULincrement\NUL\NUL\NUL\NUL\EM\EOT\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EM\EOT\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EM\EOT\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL"}'
and 0.000000 CCD from account
'3SB8kJchHEn1RLYqfuCwi1hsQaXvKVmUa9dxMAZGPKhwnpJavP' to contract
'<1049, 0>'
```

#### Todo

In the __client__, when a receive function parameter is present in a transaction outcome:
- [X] Attempt to deserialize the receive function parameter to JSON when receive function schema is present.
- [X] Output the raw parameter as hexadecimal if no schema is present or if the deserialization failed.

In the __wallet proxy__:
- [x] Updating dependency on `concordium-client` prints receive function parameters as hexadecimal.
